import numpy as np
from typing import Callable, List, Any

class NormalProposal:
    """Proposal distribution that adds normally distributed noise to the current sample."""
    def __init__(self, scale: float):
        self.scale = scale

    def __call__(self, sample: np.ndarray) -> np.ndarray:
        jump = np.random.normal(scale=self.scale, size=sample.shape)
        return sample + jump

class MetropolisSampler:
    """Metropolis-Hastings MCMC sampler."""
    
    def __init__(
        self,
        target: Callable[[np.ndarray], float],
        initial: Callable[[], np.ndarray],
        proposal: Callable[[np.ndarray], np.ndarray],
        iterations: int = 10_000
    ):
        """
        Initialize the Metropolis sampler.
        
        Args:
            target: Target probability density function (unnormalized)
            initial: Function that returns initial sample
            proposal: Function that generates proposals from current sample
            iterations: Number of iterations to run
        """
        self.target = target
        self.initial = initial
        self.proposal = proposal
        self.iterations = iterations
        self.samples = []
        self.acceptance_rate = 0.0  # Track acceptance rate
        
    def run(self) -> List[np.ndarray]:
        """Run the Metropolis algorithm and return samples."""
        self.samples = [self.initial()]
        accepted = 0  # Counter for accepted proposals
        
        for _ in range(self.iterations):
            current = self.samples[-1]
            proposed = self.proposal(current)
            
            # Calculate acceptance ratio
            acceptance_ratio = self.target(proposed) / self.target(current)
            
            # Accept or reject
            if np.random.random() < acceptance_ratio:
                self.samples.append(proposed)
                accepted += 1
            else:
                self.samples.append(current)
        
        # Store acceptance rate
        self.acceptance_rate = accepted / self.iterations
        print(f"Metropolis acceptance rate: {self.acceptance_rate:.2%}")
        return self.samples
    
    def get_samples(self) -> List[np.ndarray]:
        """Get the samples generated by the sampler."""
        return self.samples
    
    def get_acceptance_rate(self) -> float:
        """Get the acceptance rate from the last run."""
        return self.acceptance_rate
